org.gradle.jvmargs=-Xmx2048m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
android.nonTransitiveRClass=true
android.enableJetifier=false
android.defaults.buildfeatures.buildconfig=false
android.useAndroidX=true
