plugins {
    id 'com.android.application'
}
android {
    namespace 'com.leonteam.sourceweb'
    compileSdk 35
    defaultConfig {
        applicationId 'com.leonteam.sourceweb'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation 'androidx.core:core:1.13.1'
}
